enum AuthTypes {
  LOGIN_USER = 'LOGIN_USER',
  LOGIN_USER_FULFILLED = 'LOGIN_USER_FULFILLED',
  LOGIN_USER_REJECTED = 'LOGIN_USER_REJECTED',
  LOGIN_USER_PENDING = 'LOGIN_USER_PENDING',
  LOGOUT_USER = 'LOGOUT_USER',
  REGISTER_USER = 'REGISTER_USER',
  REGISTER_USER_FULFILLED = 'REGISTER_USER_FULFILLED',
  REGISTER_USER_REJECTED = 'REGISTER_USER_REJECTED',
  REGISTER_USER_PENDING = 'REGISTER_USER_PENDING'
}

export default AuthTypes;
