enum clockTypes {
  PROFILE_DATA = 'PROFILE_DATA',
  PROFILE_DATA_FULFILLED = 'PROFILE_DATA_FULFILLED',
  PROFILE_DATA_REJECTED = 'PROFILE_DATA_REJECTED',
  PROFILE_DATA_PENDING = 'PROFILE_DATA_PENDING'
}

export default clockTypes;
